services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Named volume stored under Docker's managed storage
    restart: always

volumes:
  pg_data:
